package util

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"
)

func AutoDetectLanguage(srcDir string) (string, error) {
	var extCount = make(map[string]int)

	list, err := WalkDir(srcDir)
	if err != nil {
		return "", err
	}
	for _, path := range list {
		extension := filepath.Ext(path)
		prev, prs := extCount[extension]
		if prs {
			extCount[extension] = prev + 1
		} else {
			extCount[extension] = 1
		}
	}

	delete(extCount, ".txt")
	delete(extCount, ".log")
	delete(extCount, ".in")
	delete(extCount, ".out")

	var mostFrequentExtension string
	var maxFreq = 0
	for ext, count := range extCount {
		if count > maxFreq {
			mostFrequentExtension = ext
			maxFreq = count
		}
	}
	if maxFreq == 0 {
		return "", fmt.Errorf("no valid file in src dir %s", srcDir)
	}

	lang, err := ExtensionToLanguge(mostFrequentExtension)
	if err != nil {
		return "", err
	}
	return lang, nil
}

func ExtensionToLanguge(ext string) (lang string, err error) {
	ext = strings.TrimLeft(ext, ".")
	lang, prs := extensionToPLName[ext]
	if !prs {
		return "", fmt.Errorf("%s is not a valid extension", ext)
	}
	return strings.ToLower(lang), nil
}

func FilterSrcsByLang(dir string, langExpected string) ([]string, error) {
	var err error

	if langExpected == "" {
		return nil, errors.New("provide language for filter by")
	}
	rawList, err := ListDir(dir)
	if err != nil {
		return nil, err
	}
	res := make([]string, 0)
	for _, file := range rawList {
		ext := filepath.Ext(file)
		if langActual, err := ExtensionToLanguge(ext); err != nil {
			continue
		} else if langExpected == langActual {
			res = append(res, dir+"/"+file)
		}
	}
	return res, nil
}

var extensionToPLName = map[string]string{
	"1":               "Groff",
	"1in":             "Groff",
	"1m":              "Groff",
	"1x":              "Groff",
	"2":               "Groff",
	"3":               "Groff",
	"3in":             "Groff",
	"3m":              "Groff",
	"3qt":             "Groff",
	"3x":              "Groff",
	"4":               "Groff",
	"5":               "Groff",
	"6":               "Groff",
	"7":               "Groff",
	"8":               "Groff",
	"9":               "Groff",
	"a51":             "Assembly",
	"abap":            "ABAP",
	"ada":             "Ada",
	"adb":             "Ada",
	"adoc":            "AsciiDoc",
	"ado":             "Stata",
	"adp":             "Tcl",
	"ads":             "Ada",
	"agda":            "Agda",
	"ahk":             "AutoHotkey",
	"ahkl":            "AutoHotkey",
	"aj":              "AspectJ",
	"al":              "Perl",
	"als":             "Alloy",
	"ampl":            "AMPL",
	"anim":            "Unity3D Asset",
	"ant":             "XML",
	"apacheconf":      "ApacheConf",
	"apib":            "API Blueprint",
	"apl":             "APL",
	"applescript":     "AppleScript",
	"arc":             "Arc",
	"arpa":            "DNS Zone",
	"as":              "ActionScript",
	"asax":            "ASP",
	"asciidoc":        "AsciiDoc",
	"asc":             "Public Key",
	"ascx":            "ASP",
	"asd":             "Common Lisp",
	"ash":             "AGS Script",
	"ashx":            "ASP",
	"asm":             "Assembly",
	"asmx":            "ASP",
	"asp":             "ASP",
	"aspx":            "ASP",
	"asset":           "Unity3D Asset",
	"au3":             "AutoIt",
	"aug":             "Augeas",
	"auk":             "Awk",
	"aux":             "TeX",
	"awk":             "Awk",
	"aw":              "PHP",
	"axd":             "ASP",
	"axi":             "NetLinx",
	"axml":            "XML",
	"axs":             "NetLinx",
	"bash":            "Shell",
	"bas":             "Visual Basic",
	"bat":             "Batchfile",
	"bats":            "Shell",
	"bb":              "BlitzBasic",
	"bbx":             "TeX",
	"befunge":         "Befunge",
	"bf":              "HyPhy",
	"bib":             "TeX",
	"bison":           "Bison",
	"b":               "Limbo",
	"bmx":             "BlitzMax",
	"bones":           "JavaScript",
	"boo":             "Boo",
	"boot":            "Clojure",
	"brd":             "KiCad",
	"bro":             "Bro",
	"brs":             "Brightscript",
	"bsv":             "Bluespec",
	"builder":         "Ruby",
	"bzl":             "Python",
	"cake":            "CoffeeScript",
	"cats":            "C",
	"cbl":             "COBOL",
	"cbx":             "TeX",
	"c":               "C",
	"c++":             "C++",
	"cc":              "C++",
	"ccp":             "COBOL",
	"ccxml":           "XML",
	"cdf":             "Mathematica",
	"ceylon":          "Ceylon",
	"cfc":             "ColdFusion CFC",
	"cfg":             "INI",
	"cfm":             "ColdFusion",
	"cfml":            "ColdFusion",
	"cgi":             "Shell",
	"chpl":            "Chapel",
	"chs":             "C2hs Haskell",
	"ch":              "xBase",
	"cirru":           "Cirru",
	"cjsx":            "CoffeeScript",
	"ck":              "ChucK",
	"cl2":             "Clojure",
	"click":           "Click",
	"clixml":          "XML",
	"cljc":            "Clojure",
	"clj":             "Clojure",
	"cljs":            "Clojure",
	"cljscm":          "Clojure",
	"cljx":            "Clojure",
	"cl":              "OpenCL",
	"clp":             "CLIPS",
	"cls":             "Visual Basic",
	"clw":             "Clarion",
	"cmake":           "CMake",
	"cmd":             "Batchfile",
	"cob":             "COBOL",
	"cobol":           "COBOL",
	"_coffee":         "CoffeeScript",
	"coffee":          "CoffeeScript",
	"com":             "DIGITAL Command Language",
	"command":         "Shell",
	"coq":             "Coq",
	"cp":              "Component Pascal",
	"cpp":             "C++",
	"cppobjdump":      "Cpp-ObjDump",
	"cproject":        "XML",
	"cps":             "Component Pascal",
	"cpy":             "COBOL",
	"cql":             "SQL",
	"cr":              "Crystal",
	"creole":          "Creole",
	"csh":             "Tcsh",
	"cshtml":          "C#",
	"csl":             "XML",
	"cson":            "CoffeeScript",
	"csproj":          "XML",
	"css":             "CSS",
	"cs":              "Smalltalk",
	"csv":             "CSV",
	"csx":             "C#",
	"ctp":             "PHP",
	"ct":              "XML",
	"cu":              "Cuda",
	"cuh":             "Cuda",
	"cw":              "Redcode",
	"cxx":             "C++",
	"cy":              "Cycript",
	"darcspatch":      "Darcs Patch",
	"dart":            "Dart",
	"dats":            "ATS",
	"db2":             "SQLPL",
	"dcl":             "Clean",
	"ddl":             "SQL",
	"decls":           "BlitzBasic",
	"desktop":         "desktop",
	"dfm":             "Pascal",
	"di":              "D",
	"diff":            "Diff",
	"ditamap":         "XML",
	"ditaval":         "XML",
	"dita":            "XML",
	"djs":             "Dogescript",
	"dlm":             "IDL",
	"d":               "Makefile",
	"dm":              "DM",
	"dockerfile":      "Dockerfile",
	"doh":             "Stata",
	"do":              "Stata",
	"dot":             "Graphviz (DOT)",
	"dotsettings":     "XML",
	"dpatch":          "Darcs Patch",
	"dpr":             "Pascal",
	"druby":           "Mirah",
	"dtx":             "TeX",
	"duby":            "Mirah",
	"dyalog":          "APL",
	"dylan":           "Dylan",
	"dyl":             "Dylan",
	"ebuild":          "Gentoo Ebuild",
	"ec":              "eC",
	"eclass":          "Gentoo Eclass",
	"ecl":             "ECLiPSe",
	"eclxml":          "ECL",
	"edn":             "edn",
	"E":               "E",
	"e":               "Eiffel",
	"eex":             "HTML+EEX",
	"eh":              "eC",
	"el":              "Emacs Lisp",
	"eliomi":          "OCaml",
	"eliom":           "OCaml",
	"elm":             "Elm",
	"emacs":           "Emacs Lisp",
	"emberscript":     "EmberScript",
	"em":              "EmberScript",
	"epj":             "Ecere Projects",
	"eps":             "PostScript",
	"erb":             "HTML+ERB",
	"erl":             "Erlang",
	"es6":             "JavaScript",
	"escript":         "Erlang",
	"es":              "JavaScript",
	"ex":              "Elixir",
	"exs":             "Elixir",
	"f03":             "FORTRAN",
	"f08":             "FORTRAN",
	"f77":             "FORTRAN",
	"f90":             "FORTRAN",
	"f95":             "FORTRAN",
	"factor":          "Factor",
	"fancypack":       "Fancy",
	"fan":             "Fantom",
	"fcgi":            "Shell",
	"feature":         "Cucumber",
	"f":               "Forth",
	"filters":         "XML",
	"fish":            "fish",
	"flex":            "JFlex",
	"flux":            "FLUX",
	"for":             "Forth",
	"forth":           "Forth",
	"fp":              "GLSL",
	"fpp":             "FORTRAN",
	"frag":            "JavaScript",
	"frg":             "GLSL",
	"frm":             "Visual Basic",
	"fr":              "Text",
	"frt":             "Forth",
	"frx":             "Visual Basic",
	"fs":              "GLSL",
	"fshader":         "GLSL",
	"fsh":             "GLSL",
	"fsi":             "F#",
	"fsproj":          "XML",
	"fsx":             "F#",
	"fth":             "Forth",
	"ftl":             "FreeMarker",
	"fun":             "Standard ML",
	"fxh":             "HLSL",
	"fx":              "HLSL",
	"fxml":            "XML",
	"fy":              "Fancy",
	"g4":              "ANTLR",
	"gap":             "GAP",
	"gawk":            "Awk",
	"gcode":           "G-code",
	"gco":             "G-code",
	"gd":              "GDScript",
	"gemspec":         "Ruby",
	"geo":             "GLSL",
	"geojson":         "JSON",
	"geom":            "GLSL",
	"gf":              "Grammatical Framework",
	"g":               "GAP",
	"gi":              "GAP",
	"glade":           "XML",
	"glf":             "Glyph",
	"glsl":            "GLSL",
	"glslv":           "GLSL",
	"gml":             "XML",
	"gms":             "GAMS",
	"gnu":             "Gnuplot",
	"gnuplot":         "Gnuplot",
	"god":             "Ruby",
	"go":              "Go",
	"golo":            "Golo",
	"gp":              "Gnuplot",
	"grace":           "Grace",
	"gradle":          "Gradle",
	"graphql":         "GraphQL",
	"groovy":          "Groovy",
	"grt":             "Groovy",
	"grxml":           "XML",
	"gshader":         "GLSL",
	"gs":              "JavaScript",
	"gsp":             "Groovy Server Pages",
	"gst":             "Gosu",
	"gsx":             "Gosu",
	"gtpl":            "Groovy",
	"gv":              "Graphviz (DOT)",
	"gvy":             "Groovy",
	"gyp":             "Python",
	"haml":            "Haml",
	"handlebars":      "Handlebars",
	"hats":            "ATS",
	"hb":              "Harbour",
	"hbs":             "Handlebars",
	"h++":             "C++",
	"hcl":             "HCL",
	"hh":              "Hack",
	"hic":             "Clojure",
	"hlean":           "Lean",
	"hlsl":            "HLSL",
	"hlsli":           "HLSL",
	"h":               "Objective-C",
	"hpp":             "C++",
	"hqf":             "SQF",
	"hrl":             "Erlang",
	"hsc":             "Haskell",
	"hs":              "Haskell",
	"htm":             "HTML",
	"html":            "HTML",
	"http":            "HTTP",
	"hx":              "Haxe",
	"hxsl":            "Haxe",
	"hxx":             "C++",
	"hy":              "Hy",
	"i7x":             "Inform 7",
	"iced":            "CoffeeScript",
	"icl":             "Clean",
	"idc":             "C",
	"idr":             "Idris",
	"ihlp":            "Stata",
	"ijs":             "J",
	"ik":              "Ioke",
	"ily":             "LilyPond",
	"iml":             "XML",
	"inc":             "SourcePawn",
	"ini":             "INI",
	"inl":             "C++",
	"ino":             "Arduino",
	"ins":             "TeX",
	"intr":            "Dylan",
	"io":              "Io",
	"ipf":             "IGOR Pro",
	"ipp":             "C++",
	"ipynb":           "Jupyter Notebook",
	"irbrc":           "Ruby",
	"irclog":          "IRC log",
	"iss":             "Inno Setup",
	"ivy":             "XML",
	"jade":            "Jade",
	"jake":            "JavaScript",
	"java":            "Java",
	"jbuilder":        "Ruby",
	"jelly":           "XML",
	"jflex":           "JFlex",
	"jinja":           "HTML+Django",
	"jl":              "Julia",
	"j":               "Objective-J",
	"jq":              "JSONiq",
	"jsb":             "JavaScript",
	"jscad":           "JavaScript",
	"jsfl":            "JavaScript",
	"_js":             "JavaScript",
	"js":              "JavaScript",
	"jsm":             "JavaScript",
	"json5":           "JSON5",
	"json":            "JSON",
	"jsonld":          "JSONLD",
	"jsp":             "Java Server Pages",
	"jsproj":          "XML",
	"jss":             "JavaScript",
	"jsx":             "JSX",
	"kicad_pcb":       "KiCad",
	"kid":             "Genshi",
	"kit":             "Kit",
	"kml":             "XML",
	"krl":             "KRL",
	"ksh":             "Shell",
	"kt":              "Kotlin",
	"ktm":             "Kotlin",
	"kts":             "Kotlin",
	"lagda":           "Literate Agda",
	"las":             "Lasso",
	"lasso8":          "Lasso",
	"lasso9":          "Lasso",
	"lasso":           "Lasso",
	"latte":           "Latte",
	"launch":          "XML",
	"lbx":             "TeX",
	"ld":              "Linker Script",
	"ldml":            "Lasso",
	"lds":             "Linker Script",
	"lean":            "Lean",
	"less":            "Less",
	"lex":             "Lex",
	"lfe":             "LFE",
	"lgt":             "Logtalk",
	"lhs":             "Literate Haskell",
	"lid":             "Dylan",
	"lidr":            "Idris",
	"liquid":          "Liquid",
	"lisp":            "NewLisp",
	"litcoffee":       "Literate CoffeeScript",
	"ll":              "LLVM",
	"lmi":             "Python",
	"lock":            "JSON",
	"logtalk":         "Logtalk",
	"lol":             "LOLCODE",
	"lookml":          "LookML",
	"l":               "PicoLisp",
	"lpr":             "Pascal",
	"_ls":             "LiveScript",
	"lsl":             "LSL",
	"ls":              "LoomScript",
	"lslp":            "LSL",
	"lsp":             "NewLisp",
	"ltx":             "TeX",
	"lua":             "Lua",
	"lvproj":          "LabVIEW",
	"ly":              "LilyPond",
	"m4":              "M4Sugar",
	"mak":             "Makefile",
	"mako":            "Mako",
	"ma":              "Mathematica",
	"man":             "Groff",
	"mao":             "Mako",
	"markdown":        "Markdown",
	"mask":            "Mask",
	"matah":           "Stata",
	"mata":            "Stata",
	"mathematica":     "Mathematica",
	"matlab":          "Matlab",
	"mat":             "Unity3D Asset",
	"mawk":            "Awk",
	"maxhelp":         "Max",
	"maxpat":          "Max",
	"maxproj":         "Max",
	"mcr":             "MAXScript",
	"md":              "Markdown",
	"mdpolicy":        "XML",
	"mediawiki":       "MediaWiki",
	"me":              "Groff",
	"metal":           "Metal",
	"meta":            "Unity3D Asset",
	"minid":           "MiniD",
	"mirah":           "Mirah",
	"mir":             "Mirah",
	"mkd":             "Markdown",
	"mkdn":            "Markdown",
	"mkdown":          "Markdown",
	"mkfile":          "Makefile",
	"mkii":            "TeX",
	"mkiv":            "TeX",
	"mk":              "Makefile",
	"mkvi":            "TeX",
	"ml4":             "OCaml",
	"mli":             "OCaml",
	"mll":             "OCaml",
	"ml":              "OCaml",
	"ML":              "Standard ML",
	"mly":             "OCaml",
	"mmk":             "Module Management System",
	"mms":             "Module Management System",
	"mm":              "XML",
	"m":               "Objective-C",
	"mod":             "XML",
	"mo":              "Modelica",
	"monkey":          "Monkey",
	"moo":             "Moocode",
	"moon":            "MoonScript",
	"ms":              "MAXScript",
	"mspec":           "Ruby",
	"mss":             "CartoCSS",
	"mt":              "Mathematica",
	"mtml":            "MTML",
	"muf":             "MUF",
	"mumps":           "M",
	"mu":              "mupad",
	"mustache":        "HTML+Django",
	"mxml":            "XML",
	"mxt":             "Max",
	"myt":             "Myghty",
	"nasm":            "Assembly",
	"nawk":            "Awk",
	"nbp":             "Mathematica",
	"nb":              "Text",
	"ncl":             "Text",
	"nc":              "nesC",
	"nginxconf":       "Nginx",
	"ni":              "Inform 7",
	"nim":             "Nimrod",
	"nimrod":          "Nimrod",
	"ninja":           "Ninja",
	"nit":             "Nit",
	"nix":             "Nix",
	"njs":             "JavaScript",
	"nl":              "NewLisp",
	"nlogo":           "NetLogo",
	"n":               "Nemerle",
	"no":              "Text",
	"nproj":           "XML",
	"nqp":             "Perl6",
	"nse":             "Lua",
	"nsh":             "NSIS",
	"nsi":             "NSIS",
	"numpy":           "NumPy",
	"numpyw":          "NumPy",
	"numsc":           "NumPy",
	"nu":              "Nu",
	"nuspec":          "XML",
	"nut":             "Squirrel",
	"ny":              "Common Lisp",
	"objdump":         "ObjDump",
	"odd":             "XML",
	"omgrofl":         "Omgrofl",
	"ooc":             "ooc",
	"opal":            "Opal",
	"opa":             "Opa",
	"opencl":          "OpenCL",
	"org":             "Org",
	"osm":             "XML",
	"owl":             "Web Ontology Language",
	"oxh":             "Ox",
	"oxo":             "Ox",
	"ox":              "Ox",
	"oxygene":         "Oxygene",
	"oz":              "Oz",
	"p6l":             "Perl6",
	"p6m":             "Perl6",
	"p6":              "Perl6",
	"pac":             "JavaScript",
	"pan":             "Pan",
	"parrot":          "Parrot",
	"pasm":            "Parrot Assembly",
	"pas":             "Pascal",
	"patch":           "Diff",
	"pat":             "Max",
	"pbi":             "PureBasic",
	"pb":              "PureBasic",
	"pck":             "PLSQL",
	"pde":             "Processing",
	"pd_lua":          "Lua",
	"pd":              "Pure Data",
	"perl":            "Perl",
	"php3":            "PHP",
	"php4":            "PHP",
	"php5":            "PHP",
	"ph":              "Perl",
	"php":             "PHP",
	"phps":            "PHP",
	"phpt":            "PHP",
	"phtml":           "HTML+PHP",
	"pig":             "PigLatin",
	"pike":            "Pike",
	"pir":             "Parrot Internal Representation",
	"pkb":             "PLSQL",
	"pkl":             "Pickle",
	"pks":             "PLSQL",
	"pl6":             "Perl6",
	"plb":             "PLSQL",
	"plist":           "XML",
	"plot":            "Gnuplot",
	"pl":              "Prolog",
	"pls":             "PLSQL",
	"plsql":           "PLSQL",
	"plt":             "Gnuplot",
	"pluginspec":      "XML",
	"plx":             "Perl",
	"pm6":             "Perl6",
	"pmod":            "Pike",
	"pm":              "Perl6",
	"pod":             "Pod",
	"podsl":           "Common Lisp",
	"podspec":         "Ruby",
	"po":              "Gettext Catalog",
	"pogo":            "PogoScript",
	"pony":            "Pony",
	"p":               "OpenEdge ABL",
	"pot":             "Gettext Catalog",
	"pov":             "POV-Ray SDL",
	"pp":              "Puppet",
	"prc":             "SQL",
	"prefab":          "Unity3D Asset",
	"prefs":           "INI",
	"prg":             "xBase",
	"pri":             "QMake",
	"prolog":          "Prolog",
	"properties":      "INI",
	"props":           "XML",
	"pro":             "QMake",
	"proto":           "Protocol Buffer",
	"prw":             "xBase",
	"ps1":             "PowerShell",
	"ps1xml":          "XML",
	"psc1":            "XML",
	"psc":             "Papyrus",
	"psd1":            "PowerShell",
	"psgi":            "Perl",
	"psm1":            "PowerShell",
	"ps":              "PostScript",
	"pt":              "XML",
	"pub":             "Public Key",
	"purs":            "PureScript",
	"pwn":             "PAWN",
	"pxd":             "Cython",
	"pxi":             "Cython",
	"pyde":            "Python",
	"pyp":             "Python",
	"py":              "Python",
	"pytb":            "Python traceback",
	"pyt":             "Python",
	"pyw":             "Python",
	"pyx":             "Cython",
	"qbs":             "QML",
	"qml":             "QML",
	"r2":              "Rebol",
	"r3":              "Rebol",
	"rabl":            "Ruby",
	"rake":            "Ruby",
	"raml":            "RAML",
	"raw":             "Raw token data",
	"rbbas":           "REALbasic",
	"rbfrm":           "REALbasic",
	"rbmnu":           "REALbasic",
	"rbres":           "REALbasic",
	"rb":              "Ruby",
	"rbtbar":          "REALbasic",
	"rbuild":          "Ruby",
	"rbuistate":       "REALbasic",
	"rbw":             "Ruby",
	"rbx":             "Ruby",
	"rbxs":            "Lua",
	"rdf":             "XML",
	"rdoc":            "RDoc",
	"rd":              "R",
	"rebol":           "Rebol",
	"reb":             "Rebol",
	"red":             "Red",
	"reds":            "Red",
	"reek":            "YAML",
	"rest":            "reStructuredText",
	"rg":              "Rouge",
	"rhtml":           "RHTML",
	"rktd":            "Racket",
	"rktl":            "Racket",
	"rkt":             "Racket",
	"rl":              "Ragel in Ruby Host",
	"rmd":             "RMarkdown",
	"rno":             "Groff",
	"robot":           "RobotFramework",
	"roff":            "Groff",
	"ron":             "Markdown",
	"rq":              "SPARQL",
	"r":               "Rebol",
	"rsh":             "RenderScript",
	"rs":              "Rust",
	"rss":             "XML",
	"rst":             "reStructuredText",
	"rsx":             "R",
	"ruby":            "Ruby",
	"ru":              "Ruby",
	"rviz":            "YAML",
	"sage":            "Sage",
	"sagews":          "Sage",
	"sas":             "SAS",
	"sass":            "Sass",
	"sats":            "ATS",
	"sbt":             "Scala",
	"scad":            "OpenSCAD",
	"scala":           "Scala",
	"scaml":           "Scaml",
	"scd":             "SuperCollider",
	"sce":             "Scilab",
	"sch":             "KiCad",
	"sci":             "Scilab",
	"scm":             "Scheme",
	"scpt":            "AppleScript",
	"scrbl":           "Racket",
	"scss":            "SCSS",
	"sc":              "SuperCollider",
	"scxml":           "XML",
	"self":            "Self",
	"sexp":            "Common Lisp",
	"s":               "GAS",
	"shader":          "GLSL",
	"shen":            "Shen",
	"sh":              "Shell",
	"sig":             "Standard ML",
	"sj":              "Objective-J",
	"sjs":             "JavaScript",
	"sld":             "Scheme",
	"slim":            "Slim",
	"sl":              "Slash",
	"sls":             "Scheme",
	"smali":           "Smali",
	"sma":             "SourcePawn",
	"sml":             "Standard ML",
	"smt2":            "SMT",
	"smt":             "SMT",
	"sparql":          "SPARQL",
	"spin":            "Propeller Spin",
	"sp":              "SourcePawn",
	"sps":             "Scheme",
	"sqf":             "SQF",
	"sql":             "SQLPL",
	"srdf":            "XML",
	"ssjs":            "JavaScript",
	"ss":              "Scheme",
	"stan":            "Stan",
	"sthlp":           "Stata",
	"ston":            "STON",
	"storyboard":      "XML",
	"st":              "Smalltalk",
	"stTheme":         "XML",
	"styl":            "Stylus",
	"sty":             "TeX",
	"sublime_metrics": "JavaScript",
	"sublime_session": "JavaScript",
	"svg":             "SVG",
	"svh":             "SystemVerilog",
	"sv":              "SystemVerilog",
	"swift":           "Swift",
	"syntax":          "YAML",
	"tab":             "SQL",
	"tac":             "Python",
	"targets":         "XML",
	"tcc":             "C++",
	"tcl":             "Tcl",
	"tcsh":            "Tcsh",
	"tea":             "Tea",
	"tex":             "TeX",
	"textile":         "Textile",
	"tf":              "HCL",
	"thor":            "Ruby",
	"thrift":          "Thrift",
	"thy":             "Isabelle",
	"tmCommand":       "XML",
	"tmLanguage":      "XML",
	"tml":             "XML",
	"tmPreferences":   "XML",
	"tmSnippet":       "XML",
	"tm":              "Tcl",
	"tmTheme":         "XML",
	"tmux":            "Shell",
	"toc":             "TeX",
	"toml":            "TOML",
	"tool":            "Shell",
	"topojson":        "JSON",
	"tpl":             "Smarty",
	"tpp":             "C++",
	"tst":             "Scilab",
	"ts":              "XML",
	"tsx":             "XML",
	"ttl":             "Turtle",
	"t":               "Turing",
	"tu":              "Turing",
	"twig":            "Twig",
	"txl":             "TXL",
	"txt":             "Text",
	"uc":              "UnrealScript",
	"udf":             "SQL",
	"ui":              "XML",
	"unity":           "Unity3D Asset",
	"uno":             "Uno",
	"upc":             "Unified Parallel C",
	"urdf":            "XML",
	"urs":             "UrWeb",
	"ur":              "UrWeb",
	"ux":              "XML",
	"vala":            "Vala",
	"vapi":            "Vala",
	"vark":            "Gosu",
	"vba":             "Visual Basic",
	"vbhtml":          "Visual Basic",
	"vbproj":          "XML",
	"vbs":             "Visual Basic",
	"vb":              "Visual Basic",
	"vcl":             "VCL",
	"vcxproj":         "XML",
	"veo":             "Verilog",
	"vert":            "GLSL",
	"vhdl":            "VHDL",
	"vhd":             "VHDL",
	"vhf":             "VHDL",
	"vhi":             "VHDL",
	"vhost":           "Nginx",
	"vho":             "VHDL",
	"vhs":             "VHDL",
	"vh":              "SystemVerilog",
	"vht":             "VHDL",
	"vhw":             "VHDL",
	"vim":             "VimL",
	"viw":             "SQL",
	"volt":            "Volt",
	"vrx":             "GLSL",
	"vshader":         "GLSL",
	"vsh":             "GLSL",
	"vssettings":      "XML",
	"vue":             "Vue",
	"v":               "Verilog",
	"vxml":            "XML",
	"watchr":          "Ruby",
	"w":               "C",
	"webidl":          "WebIDL",
	"weechatlog":      "IRC log",
	"wiki":            "MediaWiki",
	"wisp":            "wisp",
	"wl":              "Mathematica",
	"wlt":             "Mathematica",
	"wlua":            "Lua",
	"wsdl":            "XML",
	"wsf":             "XML",
	"wsgi":            "Python",
	"wxi":             "XML",
	"wxl":             "XML",
	"wxs":             "XML",
	"x10":             "X10",
	"x3d":             "XML",
	"xacro":           "XML",
	"xaml":            "XML",
	"xc":              "XC",
	"xht":             "HTML",
	"xhtml":           "HTML",
	"xib":             "XML",
	"xi":              "Logos",
	"xlf":             "XML",
	"xliff":           "XML",
	"x":               "Logos",
	"xmi":             "XML",
	"xm":              "Logos",
	"xml":             "XML",
	"xojo_code":       "Xojo",
	"xojo_menu":       "Xojo",
	"xojo_report":     "Xojo",
	"xojo_script":     "Xojo",
	"xojo_toolbar":    "Xojo",
	"xojo_window":     "Xojo",
	"xpl":             "XProc",
	"xproc":           "XProc",
	"xproj":           "XML",
	"xpy":             "Python",
	"xql":             "XQuery",
	"xqm":             "XQuery",
	"xquery":          "XQuery",
	"xq":              "XQuery",
	"xqy":             "XQuery",
	"xrl":             "Erlang",
	"xsd":             "XML",
	"xsjs":            "JavaScript",
	"xsjslib":         "JavaScript",
	"xslt":            "XSLT",
	"xsl":             "XSLT",
	"xs":              "XS",
	"xtend":           "Xtend",
	"xul":             "XML",
	"yacc":            "Yacc",
	"yaml":            "YAML",
	"yang":            "YANG",
	"yap":             "Prolog",
	"yml":             "YAML",
	"yrl":             "Erlang",
	"y":               "Yacc",
	"yy":              "Yacc",
	"zcml":            "XML",
	"zep":             "Zephir",
	"zimpl":           "Zimpl",
	"zmpl":            "Zimpl",
	"zone":            "DNS Zone",
	"zpl":             "Zimpl",
	"zsh":             "Shell",
}
